### ISSUE TITLE
ModuleNotFoundError: No module named 'speech_to_text.openai_api'

### ISSUE THREAD

**Issue by ainy0315** [reriiasu/speech-to-text#5]
C:\Users\Administrator\speech-to-text>python -m speech_to_text
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\speech-to-text\speech_to_text\__main__.py", line 7, in <module>
    from .audio_transcriber import AppOptions
  File "C:\Users\Administrator\speech-to-text\speech_to_text\audio_transcriber.py", line 15, in <module>
    from .openai_api import OpenAIAPI
ModuleNotFoundError: No module named 'speech_to_text.openai_api'
Can you tell me how to fix this? Thank you.

**Comment by reriiasu** [comment]
I have committed the missing files. Thank you for pointing that out.
